version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - ../:/workspace:cached
      - node_modules:/workspace/node_modules:cached
    tty: true
volumes:
  node_modules:
